name: 'build-test'
on: 'pull_request'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          yarn install
      - run: |
          yarn run all
  test: # make sure the action works on a clean machine without building
    permissions:
      pull-requests: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        id: validate
      - uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          header: validate-dependabot
          message: |
            ${{ steps.validate.outputs.markdown }}
            ```json
            ${{ steps.validate.outputs.raw }}
            ```
